builders:
  - python
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
python_module: haproxy_status
clean_workspace: true
publish_over_ssh:
  - pypi.sunet.se

extra_jobs:
  - name: haproxy-status-docker
    builders:
      - docker
    docker_name: haproxy-status
    managed_scripts:
      - docker_build_prep.sh
      - docker_tag.sh
    triggers:
      github_push: false
      cron: null
    upstream:
      - eduid-docker-pythonenv
