builders:
  - script
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
python_module: haproxy_status
clean_workspace: true
publish_over_ssh:
  - pypi.sunet.se

script:
  - "python3.7 -m venv venv"
  - ". venv/bin/activate"
  - "pip install --upgrade setuptools pip wheel mypy"
  - "pip install --index-url https://pypi.sunet.se -r test_requirements.txt"
  - "nosetests"
  - "mypy --ignore-missing-imports src/haproxy_status"
  - "python setup.py sdist bdist_wheel --universal"

extra_jobs:
  - name: haproxy-status-docker
    builders:
      - docker
    docker_name: haproxy-status
    managed_scripts:
      - docker_build_prep.sh
      - docker_tag.sh
    triggers:
      github_push: false
      cron: null
    upstream:
      - eduid-docker-python3env
      - haproxy-status
